Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  config.vm.define "vm1"
  config.vm.network "private_network", ip: "192.168.99.2"

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 2
    vb.memory = "2048"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "site.yml"
    ansible.groups = {
      "kafka" => ["vm1"],
      "mysql" => ["vm1"]
    }
  end

end