package com.tdc.kafka.kafka_coffee;

import com.tdc.kafka.kafka_coffee.model.Item;
import com.tdc.kafka.kafka_coffee.model.Order;
import io.reactivex.Completable;
import io.reactivex.Observable;
import io.vertx.core.json.JsonObject;
import io.vertx.reactivex.core.AbstractVerticle;
import io.vertx.reactivex.kafka.client.producer.KafkaProducer;
import io.vertx.reactivex.kafka.client.producer.KafkaProducerRecord;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.math.BigDecimal;
import java.util.HashMap;
import java.util.Map;
import java.util.Random;

/**
 * Simulate Events Generated by User Input
 */
@SuppressWarnings({"ResultOfMethodCallIgnored", "BigDecimalMethodWithoutRoundingCalled"})
public class UserInputEventStream extends AbstractVerticle {

    private static final Logger LOG = LoggerFactory.getLogger(UserInputEventStream.class);
    private static final int EVENT_PERIOD_IN_MILLISECONDS = 2000;
    private static final String KAFKA_CONFIG_KEY = "kafka";
    private static final String ORDER_SUBMITTED_TOPIC_KEY = "order.submitted.topic";

    @Override
    public Completable rxStart() {
        JsonObject externalKafkaConfig = config().getJsonObject(KAFKA_CONFIG_KEY);

        Map<String, String> prodConfig = new HashMap<>();
        prodConfig.put("bootstrap.servers", externalKafkaConfig.getString("bootstrap.servers"));
        prodConfig.put("key.serializer", "org.apache.kafka.common.serialization.StringSerializer");
        prodConfig.put("value.serializer", "org.apache.kafka.common.serialization.StringSerializer");
        prodConfig.put("acks", "1");

        KafkaProducer<String, String> producer = KafkaProducer.create(vertx, prodConfig);

        //Creating periodic stream to generate events
        vertx.periodicStream(EVENT_PERIOD_IN_MILLISECONDS).toFlowable()
                .subscribe(timeout -> {
                    Order order = createOrder(new Random().nextInt(3) + 1);
                    LOG.info("Generating order {}...", order.getId());
                    KafkaProducerRecord<String, String> record =
                            KafkaProducerRecord.create(externalKafkaConfig.getString(ORDER_SUBMITTED_TOPIC_KEY), order.getId(), JsonObject.mapFrom(order).encode());
                    producer.rxWrite(record)
                            .subscribe(recordCreated -> LOG.info("Order submission {} event created...", order.getId()),
                                    Throwable::printStackTrace);
                });

        return Completable.complete();
    }

    private final String[] prods = new String[] {"1", "2", "3"};
    private final Integer[] amounts = new Integer[] {50, 100, 1};
    private final BigDecimal[] values = new BigDecimal[] {new BigDecimal("3.50").setScale(2),new BigDecimal("2.00").setScale(2), new BigDecimal("1.50").setScale(2)};

    private Order createOrder(int numItems) {
        Order order = new Order();

        Observable.range(0, numItems)
                .forEach(index -> {
                    Item item1 = new Item();
                    item1.setProdId(prods[index]);
                    item1.setValue(values[index]);
                    item1.setAmount(amounts[index]);
                    order.addItem(item1);
                });

        order.setTotal(order.getItems().stream().map(Item::getValue).reduce(BigDecimal::add).get().setScale(2));

        return order;
    }
}
