package com.tdc.kafka.kafka_coffee;

import com.tdc.kafka.kafka_coffee.model.Item;
import com.tdc.kafka.kafka_coffee.model.Order;
import io.reactivex.Completable;
import io.reactivex.Observable;
import io.vertx.core.json.JsonObject;
import io.vertx.reactivex.core.AbstractVerticle;
import io.vertx.reactivex.kafka.client.producer.KafkaProducer;
import io.vertx.reactivex.kafka.client.producer.KafkaProducerRecord;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.math.BigDecimal;
import java.util.HashMap;
import java.util.Map;
import java.util.Random;

import static com.tdc.kafka.kafka_coffee.RepositoryVerticle.REFILL_STOCK_QUEUE;

/**
 * Simulate Events Generated by User Input
 */
@SuppressWarnings({"ResultOfMethodCallIgnored", "BigDecimalMethodWithoutRoundingCalled"})
public class UserInputEventStream extends AbstractVerticle {

    private static final Logger LOG = LoggerFactory.getLogger(UserInputEventStream.class);
    private static final int EVENT_PERIOD_IN_MILLISECONDS = 30000;

    @Override
    public Completable rxStart() {
        //Creating periodic stream to generate events
        vertx.periodicStream(EVENT_PERIOD_IN_MILLISECONDS).toFlowable()
                .subscribe(timeout -> {
                    vertx.eventBus().rxSend(REFILL_STOCK_QUEUE, "REFILL")
                            .subscribe(reply -> {
                                LOG.info("Stock refill check executed!");
                            }, error -> LOG.error(error.getMessage(), error));

                });

        return Completable.complete();
    }


}
